import { useEffect, useState } from "react";
import { FaEnvelope, FaPaperPlane } from "react-icons/fa";
import "../styles/abandoned-cart-emails.css";
const API_URL = import.meta.env.VITE_API_URL || "http://localhost:3000";
type Cart = { id:number; customer_name?:string; customer_email:string; item_count:number; total:number; updated_at:string; items?:{name:string;quantity:number}[] };
export default function AbandonedCartEmails(){
 const [carts,setCarts]=useState<Cart[]>([]),[selected,setSelected]=useState<number[]>([]),[subject,setSubject]=useState("Your SR Artémore picks are waiting"),[message,setMessage]=useState("We saved the pieces you loved. Return to your cart whenever you are ready to complete your order."),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sending,setSending]=useState(false),[confirm,setConfirm]=useState(false),[result,setResult]=useState("");
 const headers={Authorization:`Bearer ${localStorage.getItem("adminToken")||""}`};
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(`${API_URL}/api/admin/abandoned-carts`,{headers});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Could not load persisted abandoned carts.");setCarts(d.carts||[])}catch(e){setError(e instanceof Error?e.message:"Could not load carts.")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const send=async()=>{setSending(true);setConfirm(false);setResult("");try{const r=await fetch(`${API_URL}/api/admin/abandoned-carts/send`,{method:"POST",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({cartIds:selected,subject,message})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Reminder delivery failed.");setResult(`${d.sent} reminder${d.sent===1?"":"s"} sent. ${d.failed?`${d.failed} could not be sent.`:""}`);setSelected([]);load()}catch(e){setResult(e instanceof Error?e.message:"Reminder delivery failed.")}finally{setSending(false)}};
 return <div className="abandoned-carts-page"><header><div><p className="mail-eyebrow">CUSTOMER RECOVERY</p><h1>Abandoned cart emails</h1><p>Only authenticated customers with a persisted, inactive cart are shown. Local browser carts are never available here.</p></div></header>{error?<div className="mail-error">{error}<button onClick={load}>Try again</button></div>:<div className="mail-layout"><section className="cart-list-panel"><div className="mail-panel-head"><div><h2>Eligible recipients</h2><p>{loading?"Checking carts…":`${carts.length} carts ready for a reminder`}</p></div><button onClick={()=>setSelected(selected.length===carts.length?[]:carts.map(c=>c.id))}>Select all</button></div>{!loading&&!carts.length?<div className="mail-empty"><FaEnvelope/><strong>No eligible carts</strong><span>Reminders appear after an authenticated customer leaves a saved cart inactive for 24 hours.</span></div>:<div className="cart-table"><table><thead><tr><th/><th>Customer</th><th>Cart</th><th>Last active</th></tr></thead><tbody>{carts.map(cart=><tr key={cart.id}><td><input type="checkbox" checked={selected.includes(cart.id)} aria-label={`Select ${cart.customer_email}`} onChange={()=>setSelected(selected.includes(cart.id)?selected.filter(id=>id!==cart.id):[...selected,cart.id])}/></td><td><strong>{cart.customer_name||"Customer"}</strong><small>{cart.customer_email}</small></td><td>{cart.item_count} item{cart.item_count===1?"":"s"}<small>£{Number(cart.total||0).toFixed(2)}</small></td><td>{new Date(cart.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div>}</section><aside className="compose-panel"><div className="mail-panel-head"><div><h2>Compose reminder</h2><p>Personalised cart details are added automatically.</p></div></div><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={140}/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={600}/></label><div className="email-preview"><span>EMAIL PREVIEW</span><strong>{subject}</strong><p>Hello customer,</p><p>{message}</p><em>Your saved items and a link to return to the shop will be included.</em></div>{result&&<p className="send-result">{result}</p>}<button className="send-reminders" disabled={!selected.length||sending} onClick={()=>setConfirm(true)}><FaPaperPlane/> Send to {selected.length} selected</button></aside></div>}{confirm&&<div className="confirm-layer" role="dialog" aria-modal="true"><div><h2>Send reminders?</h2><p>This sends the current subject and message to {selected.length} selected recipients. Each successful send is recorded to prevent a recent duplicate.</p><button onClick={()=>setConfirm(false)}>Cancel</button><button className="send-reminders" onClick={send}>Send reminders</button></div></div>}</div>;
}
